[
    {
        "key": "dbln",
        "value": "%7B%22100091888524172%22%3A%22TwvB4OT2%22%2C%2261566324392670%22%3A%22Z5JzJ9bW%22%7D",
        "domain": "facebook.com",
        "path": "/login/device-based/",
        "hostOnly": false,
        "creation": "2025-09-11T00:21:47.335Z",
        "lastAccessed": "2025-09-11T00:21:47.336Z"
    },
    {
        "key": "datr",
        "value": "h__BaHiQMBfc7R8_-C2z74Gu",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-11T00:21:47.336Z",
        "lastAccessed": "2025-09-11T00:21:47.336Z"
    },
    {
        "key": "sb",
        "value": "h__BaKctATk5lsYVT0rAIp0R",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-11T00:21:47.336Z",
        "lastAccessed": "2025-09-11T00:21:47.336Z"
    },
    {
        "key": "locale",
        "value": "bn_IN",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-11T00:21:47.336Z",
        "lastAccessed": "2025-09-11T00:21:47.336Z"
    },
    {
        "key": "vpd",
        "value": "v1%3B656x320x2.25",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-11T00:21:47.336Z",
        "lastAccessed": "2025-09-11T00:21:47.336Z"
    },
    {
        "key": "m_pixel_ratio",
        "value": "2.25",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-11T00:21:47.336Z",
        "lastAccessed": "2025-09-11T00:21:47.336Z"
    },
    {
        "key": "wd",
        "value": "320x734",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-11T00:21:47.336Z",
        "lastAccessed": "2025-09-11T00:21:47.336Z"
    },
    {
        "key": "c_user",
        "value": "61566324392670",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-11T00:21:47.336Z",
        "lastAccessed": "2025-09-11T00:21:47.336Z"
    },
    {
        "key": "xs",
        "value": "27%3AJsc6oeB1gHMTog%3A2%3A1757550054%3A-1%3A-1",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-11T00:21:47.336Z",
        "lastAccessed": "2025-09-11T00:21:47.336Z"
    },
    {
        "key": "fr",
        "value": "0le0g7idsMxyNxDe1.AWc9DxFtv3o5g-7ZWypLaHpZrm6DnQ3lb_ZTGyaWRUSCHNtY6N0.Bowf-H..AAA.0.0.BowhXr.AWdN2D_Tb11P5ZyUkltnFVYDgBQ",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-11T00:21:47.336Z",
        "lastAccessed": "2025-09-11T00:21:47.336Z"
    },
    {
        "key": "pas",
        "value": "100091888524172%3AzjZFtShoWs%2C61566324392670%3ArSVIQgGjTV",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-11T00:21:47.336Z",
        "lastAccessed": "2025-09-11T00:21:47.336Z"
    },
    {
        "key": "fbl_st",
        "value": "100733109%3BT%3A29292501",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-11T00:21:47.336Z",
        "lastAccessed": "2025-09-11T00:21:47.336Z"
    },
    {
        "key": "wl_cbv",
        "value": "v2%3Bclient_version%3A2919%3Btimestamp%3A1757550060",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-11T00:21:47.336Z",
        "lastAccessed": "2025-09-11T00:21:47.336Z"
    }
]
