
[
    {
        "key": "dbln",
        "value": "%7B%22100091888524172%22%3A%22TwvB4OT2%22%7D",
        "domain": "facebook.com",
        "path": "/login/device-based/",
        "hostOnly": false,
        "creation": "2025-09-11T00:17:13.175Z",
        "lastAccessed": "2025-09-11T00:17:13.176Z"
    },
    {
        "key": "datr",
        "value": "h__BaHiQMBfc7R8_-C2z74Gu",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-11T00:17:13.176Z",
        "lastAccessed": "2025-09-11T00:17:13.176Z"
    },
    {
        "key": "sb",
        "value": "h__BaKctATk5lsYVT0rAIp0R",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-11T00:17:13.176Z",
        "lastAccessed": "2025-09-11T00:17:13.176Z"
    },
    {
        "key": "c_user",
        "value": "100091888524172",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-11T00:17:13.176Z",
        "lastAccessed": "2025-09-11T00:17:13.176Z"
    },
    {
        "key": "xs",
        "value": "49%3AmhekdoXGGZccZg%3A2%3A1757544381%3A-1%3A-1",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-11T00:17:13.176Z",
        "lastAccessed": "2025-09-11T00:17:13.176Z"
    },
    {
        "key": "locale",
        "value": "bn_IN",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-11T00:17:13.176Z",
        "lastAccessed": "2025-09-11T00:17:13.176Z"
    },
    {
        "key": "pas",
        "value": "100091888524172%3AzjZFtShoWs",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-11T00:17:13.176Z",
        "lastAccessed": "2025-09-11T00:17:13.176Z"
    },
    {
        "key": "vpd",
        "value": "v1%3B656x320x2.25",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-11T00:17:13.176Z",
        "lastAccessed": "2025-09-11T00:17:13.176Z"
    },
    {
        "key": "fr",
        "value": "0le0g7idsMxyNxDe1.AWffszOueb7WasCVFSwVbFNUr_t9feY7naZwvFC0wFdolcniEqA.Bowf-H..AAA.0.0.BowhTC.AWddbxdfWKOeAbXJMIFZzgpr6bE",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-11T00:17:13.176Z",
        "lastAccessed": "2025-09-11T00:17:13.176Z"
    },
    {
        "key": "fbl_st",
        "value": "100430123%3BT%3A29292496",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-11T00:17:13.176Z",
        "lastAccessed": "2025-09-11T00:17:13.176Z"
    },
    {
        "key": "wl_cbv",
        "value": "v2%3Bclient_version%3A2919%3Btimestamp%3A1757549762",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-11T00:17:13.176Z",
        "lastAccessed": "2025-09-11T00:17:13.176Z"
    }
]
